### PR TITLE
update nlp notebook

### PR DESCRIPTION
**Pull request by liususan091219**
## Why are these changes needed?

Update nlp notebook in main branch to latest

## Checks

- [x] I've used [pre-commit](https://microsoft.github.io/FLAML/docs/Contribute#pre-commit) to lint the changes in this PR, or I've made sure [lint with flake8](https://github.com/microsoft/FLAML/blob/816a82a1155b4de4705b21a615ccdff67c6da379/.github/workflows/python-package.yml#L54-L59) output is two 0s.
- [ ] I've included any doc changes needed for https://microsoft.github.io/FLAML/. See https://microsoft.github.io/FLAML/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by sonichi** [comment]
1. The URL markdown doesn't work for some reason: 
image
2. The learning curve before 4.2 doesn't look good:
image
3. Too many redundant and useless messages like:
image
image
4. Is it safe to ignore warning like this?
image

**Comment by liususan091219** [comment]
> 1. The URL markdown doesn't work for some reason:
>    image
> 2. The learning curve before 4.2 doesn't look good:
>    image
> 3. Too many redundant and useless messages like:
>    image
>    image
> 4. Is it safe to ignore warning like this?
>    image

1: addressed
2: will rerun with longer time
3: will delete manually
4: This warning is for deletion, so should be fine.

**Comment by sonichi** [comment]
3 and 4 are not addressed satisfactorily.

**Comment by thinkall** [comment]
The notebook contains many unnecessary information, making it a very large file. Would be nice to remove all the `widgets` and `colab` metadata. It ends up with 2000+ lines and 200k by removing colab metadata and widgets while keep all the outputs as I tested in my local machine.

**Comment by liususan091219** [comment]
@thinkall thanks, could you share how you were able to remove all the widget and colab metadata?

**Comment by liususan091219** [comment]
> 3 and 4 are not addressed satisfactorily.

They are both addressed now.

**Review by sonichi — APPROVED** [review]

**Review by thinkall — APPROVED** [review]

**Pull request merged**
