### PR TITLE
Improve auto reply registration

### PR DESCRIPTION
**Pull request by sonichi**
## Why are these changes needed?

1. Make _check_termination_and_human_reply a registered method so that other functions can be registered before it.
2. Make registration position configurable.
3. Allow registered functions to be excluded in `generate_reply`.
4. Remove the need for overriding `generate_reply` completely.
5. Update the chess and groupchat notebooks.
6. Use object as key.
7. Add link to the groupchat notebook.
8. Fix bug in mathchat.
9. Allow send/receive without reply and simplify the groupchat implementation.

## Checks

- [x] I've included any doc changes needed for https://microsoft.github.io/FLAML/. See https://microsoft.github.io/FLAML/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by BeibinLi — APPROVED** [review]
LGTM

**Review by thinkall — APPROVED** [review]
Would a function `unregister_auto_reply` be useful? Just a random thought, no actual use case from my side.

**Comment by thinkall** [comment]
https://github.com/microsoft/FLAML/actions/runs/5756114523/job/15604943615?pr=1170#step:12:105
```
____________________________ test_responsive_agent _____________________________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f95c06de1c0>

    def test_responsive_agent(monkeypatch):
        dummy_agent_1 = ResponsiveAgent(name="dummy_agent_1", human_input_mode="ALWAYS")
        dummy_agent_2 = ResponsiveAgent(name="dummy_agent_2", human_input_mode="TERMINATE")
    
        monkeypatch.setattr(sys, "stdin", StringIO("exit"))
        dummy_agent_1.receive("hello", dummy_agent_2)  # receive a str
        monkeypatch.setattr(sys, "stdin", StringIO("TERMINATE\n\n"))
        dummy_agent_1.receive(
            {
                "content": "hello {name}",
                "context": {
                    "name": "dummy_agent_2",
                },
            },
            dummy_agent_2,
        )  # receive a dict
>       assert "context" in dummy_agent_1.chat_messages["dummy_agent_2"][-2]
E       IndexError: list index out of range

test/autogen/agentchat/test_responsive_agent.py:[84](https://github.com/microsoft/FLAML/actions/runs/5756114523/job/15604943615?pr=1170#step:12:85): IndexError
----------------------------- Captured stdout call -----------------------------
dummy_agent_2 (to dummy_agent_1):

hello

--------------------------------------------------------------------------------
Provide feedback to dummy_agent_2. Press enter to skip and use auto-reply, or type 'exit' to end the conversation: dummy_agent_2 (to dummy_agent_1):

hello {name}

--------------------------------------------------------------------------------
Provide feedback to dummy_agent_2. Press enter to skip and use auto-reply, or type 'exit' to end the conversation: dummy_agent_1 (to dummy_agent_2):

TERMINATE

--------------------------------------------------------------------------------
Please give feedback to dummy_agent_1. Press enter or type 'exit' to stop the conversation: 
>>>>>>>> NO HUMAN INPUT RECEIVED.
```

**Comment by sonichi** [comment]
> Would a function `unregister_auto_reply` be useful? Just a random thought, no actual use case from my side.

I guess it'll be useful. We can add it when needed.

**Pull request merged**
