### PR TITLE
Refactor into automl subpackage

### PR DESCRIPTION
**Pull request by markharley**
## Why are these changes needed?
Moved some of the packages into an automl subpackage to tidy before the task-based refactor. This is in response to discussions with the group and a comment on the first task-based PR.

Only changes here are moving subpackages and modules into the new automl, fixing imports to work with this structure and fixing some dependencies in setup.py.

## Related issue number
None

## Checks

- [X] I've used [pre-commit](https://microsoft.github.io/FLAML/docs/Contribute#pre-commit) to lint the changes in this PR, or I've made sure [lint with flake8](https://github.com/microsoft/FLAML/blob/816a82a1155b4de4705b21a615ccdff67c6da379/.github/workflows/python-package.yml#L54-L59) output is two 0s.
- [X] I've included any doc changes needed for https://microsoft.github.io/FLAML/. See https://microsoft.github.io/FLAML/docs/Contribute#documentation to build and test documentation locally.
- [X] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [X] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by sonichi — COMMENTED** [review]
Structural comment: I thought `flaml.default` is a top-level package as it corresponds to one of the three use cases in documentation. Open to discussion.

**Comment by markharley** [comment]
> Structural comment: I thought `flaml.default` is a top-level package as it corresponds to one of the three use cases in documentation. Open to discussion.

Ah, okay! I moved based on usage as it wasn't imported outside of automl, but if it's part of the package interface then I'll move it back

**Review by sonichi — APPROVED** [review]
Looks good to me. Some notebooks need to be updated for the import locations. Please create an issue about it.

**Comment by qingyun-wu** [comment]
Looks good to me. But it seems there are some conflicts in the automl.py file. Could you take a look at it and resolve it?  Thank you! @markharley

**Comment by markharley** [comment]
Thanks! I've fixed that up now

**Review by qingyun-wu — APPROVED** [review]

**Comment by markharley** [comment]
Looks good to go. I've raised the license with my lead at work. Should hear back from him soon then I'll sign

**Comment by markharley** [comment]
@microsoft-github-policy-service agree [company="Wise Plc"]

**Comment by markharley** [comment]
@microsoft-github-policy-service agree

**Comment by qingyun-wu** [comment]
> @microsoft-github-policy-service agree

@markharley Thank you for signing the agreement. Some of the tests are failing now. Could you take a look at them and try to address them?

**Comment by sonichi** [comment]
> > @microsoft-github-policy-service agree
> 
> @markharley Thank you for signing the agreement. Some of the tests are failing now. Could you take a look at them and try to address them?

All PR's tests are failing. I'm trying to fix them in #826

**Comment by qingyun-wu** [comment]
> 

Thanks, @sonichi, for fixing the issues that fail the tests. @markharley, it seems after the fixes of Chi, there are conflicts that must be resolved. Could you resolve the conflicts? I will review and merge this PR after the conflicts are fixed.  Thank you!

**Pull request merged**
