### PR TITLE
constraint

### PR DESCRIPTION
**Pull request by sonichi**
Support optional constraint on training/prediction time of the model

### CODE REVIEW

**Comment by sonichi** [comment]
close #133

**Review by yue-msr — COMMENTED** [review]
Seems correct, although I do not fully understand all detail.
Are there additional test cases for different train_time_limit and pred_time_limit?

**Comment by sonichi** [comment]
> Seems correct, although I do not fully understand all detail.
> Are there additional test cases for different train_time_limit and pred_time_limit?

Have you seen
https://github.com/microsoft/FLAML/pull/132/files#diff-8b8d337b94424ebfccb1ea4d38f13958b4fa806bc0e1a9c10267da5ea24e0fb7
?

**Comment by yue-msr** [comment]
> > Seems correct, although I do not fully understand all detail.
> > Are there additional test cases for different train_time_limit and pred_time_limit?
> 
> Have you seen
> https://github.com/microsoft/FLAML/pull/132/files#diff-8b8d337b94424ebfccb1ea4d38f13958b4fa806bc0e1a9c10267da5ea24e0fb7
> ?

Yeah, I saw that, but I was wondering if we have >=2 tests for >=2 different time values. Or do you think it is unnecessary?

**Review by yue-msr — APPROVED** [review]

**Pull request merged**
