### PR TITLE
minor change to notebook

### PR DESCRIPTION
**Pull request by sonichi**
## Why are these changes needed?

Fix an indent and version number in the openai notebook.

## Checks

- [x] I've used [pre-commit](https://microsoft.github.io/FLAML/docs/Contribute#pre-commit) to lint the changes in this PR, or I've made sure [lint with flake8](https://github.com/microsoft/FLAML/blob/816a82a1155b4de4705b21a615ccdff67c6da379/.github/workflows/python-package.yml#L54-L59) output is two 0s.
- [ ] I've included any doc changes needed for https://microsoft.github.io/FLAML/. See https://microsoft.github.io/FLAML/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by thinkall — COMMENTED** [review]
Looks good to me. Just wondering why do we need to fix the version?

**Review by qingyun-wu — APPROVED** [review]

**Comment by sonichi** [comment]
> Looks good to me. Just wondering why do we need to fix the version?

Version 1.1.3 updated the price from v1.1.2. The notebook's results will be quite different when using these two different versions, including how long it takes to finish.

**Comment by thinkall** [comment]
> > Looks good to me. Just wondering why do we need to fix the version?
> 
> Version 1.1.3 updated the price from v1.1.2. The notebook's results will be quite different when using these two different versions, including how long it takes to finish.

`pip install` will always install the latest version by default. To avoid installing the eariler version, maybe better use `>=1.1.3`.

**Comment by sonichi** [comment]
> > > Looks good to me. Just wondering why do we need to fix the version?
> > 
> > 
> > Version 1.1.3 updated the price from v1.1.2. The notebook's results will be quite different when using these two different versions, including how long it takes to finish.
> 
> `pip install` will always install the latest version by default. To avoid installing the eariler version, maybe better use `>=1.1.3`.

After we release a new version and before we update the notebook, if a user executes `pip install flaml>=1.1.3`, they will see an inconsistent result. That's why I fixed the version number here.

**Review by thinkall — APPROVED** [review]

**Pull request merged**
