### PR TITLE
clean unnecessary widgets in notebook

### PR DESCRIPTION
**Pull request by thinkall**
## Why are these changes needed?

To simplify the notebooks, make it easier to compare the changes inline.

## Checks

- [x] I've used [pre-commit](https://microsoft.github.io/FLAML/docs/Contribute#pre-commit) to lint the changes in this PR, or I've made sure [lint with flake8](https://github.com/microsoft/FLAML/blob/816a82a1155b4de4705b21a615ccdff67c6da379/.github/workflows/python-package.yml#L54-L59) output is two 0s.
- [ ] I've included any doc changes needed for https://microsoft.github.io/FLAML/. See https://microsoft.github.io/FLAML/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Review by sonichi — APPROVED** [review]
I like the "open in colab" button on top. It's a good idea to add it to other applicable notebooks too.

**Comment by liususan091219** [comment]
@thinkall thanks for this. Could you share how you removed the widgets? So I could reproduce them in #940. 

This PR has not addressed some updates in PR 940 (e.g., flaml is not versioned in 940, we are no longer using ray), it may be more convenient for us to merge 940.

**Comment by thinkall** [comment]
> @thinkall thanks for this. Could you share how you removed the widgets? So I could reproduce them in #940.
> 
> This PR has not addressed some updates in PR 940 (e.g., flaml is not versioned in 940, we are no longer using ray), it may be more convenient for us to merge 940.

Sure. I removed the metadata and widgets manually. But you can also do it with `nbstripout`. Very simple command:

```shell
pip install -U nbstripout
nbstripout automl_nlp.ipynb --keep-output --extra-keys 'cell.metadata.colab'
```
It removes all the widgets and colab metadata while keep all the output info.

**Comment by liususan091219** [comment]
> > @thinkall thanks for this. Could you share how you removed the widgets? So I could reproduce them in #940.
> > This PR has not addressed some updates in PR 940 (e.g., flaml is not versioned in 940, we are no longer using ray), it may be more convenient for us to merge 940.
> 
> Sure. I removed the metadata and widgets manually. But you can also do it with `nbstripout`. Very simple command:
> 
> ```shell
> pip install -U nbstripout
> nbstripout automl_nlp.ipynb --keep-output --extra-keys 'cell.metadata.colab'
> ```
> 
> It removes all the widgets and colab metadata while keep all the output info.

Thanks for the tip!

**Comment by thinkall** [comment]
Close this one as it's solved in #940

**Pull request closed without merging**
