### PR TITLE
precommit: introduce `mdformat`

### PR DESCRIPTION
**Pull request by Borda**
## Why are these changes needed?

This is systematic solution to MD formatting as reported 

## Related issue number

for example, in #834

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/FLAML/. See https://microsoft.github.io/FLAML/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by Borda** [comment]
the core change is 14fdf69, and the resulted formatting is in ac6f076

**Comment by Borda** [comment]
@sonichi @thinkall, mind check and share your opinion? :rabbit:

**Comment by Borda** [comment]
@sonichi @thinkall, how are you doing? could you have a quick look? :flamingo:

**Review by thinkall — APPROVED** [review]
Thank you @Borda , looks good to me.

**Comment by Borda** [comment]
@sonichi @jackgerrits, could you pls also have a look? :rabbit:

**Review by sonichi — APPROVED** [review]

**Pull request merged**
