### PR TITLE
set black with 120 line length

### PR DESCRIPTION
**Pull request by Borda**
## Why are these changes needed?

as Flake8 is set already to 127 line length Black has default 88 so it is natural to have both aligned, see flake8 setting: https://github.com/microsoft/FLAML/blob/f404b66a4c20d421c9cee465a6796ca76a0a8992/.flake8#L3

## Checks

- [x] I've used [pre-commit](https://microsoft.github.io/FLAML/docs/Contribute#pre-commit) to lint the changes in this PR, or I've made sure [lint with flake8](https://github.com/microsoft/FLAML/blob/816a82a1155b4de4705b21a615ccdff67c6da379/.github/workflows/python-package.yml#L54-L59) output is two 0s.
- [ ] I've included any doc changes needed for https://microsoft.github.io/FLAML/. See https://microsoft.github.io/FLAML/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by Borda** [comment]
Not sure, but the two failing test does not seem to be related to the formating update...

**Comment by skzhang1** [comment]
@Borda Thanks for your PR! Can you figure out how to address the conflicts?

**Comment by Borda** [comment]
> @Borda Thanks for your PR! Can you figure out how to address the conflicts?

Sure, it shall be trivial as the main contribution of this PR is update config, the rest is just bot work, so I will accept all changes from main branch and re-run the bot 🐰

**Comment by Borda** [comment]
@skzhang1 shall be fixed now :chipmunk:

**Review by skzhang1 — APPROVED** [review]

**Review by kevin666aa — APPROVED** [review]

**Pull request merged**
