### PR TITLE
fix #871: call check_spark only when necessary

### LINKED ISSUE #871: `AutoML.fit` always creates a spark session even when it doesn't need to
Currently, `AutoML.fit` always creates a spark session even when it doesn't need to in the following line:
https://github.com/microsoft/FLAML/blob/90aea9c28b6100faf86f2c204e53a68e87f10c66/flaml/automl/automl.py#L2607

`check_spark` calls `SparkSession.builder.getOrCreate` and creates a spark session if it doesn't exist:

https://github.com/microsoft/FLAML/blob/90aea9c28b6100faf86f2c204e53a68e87f10c66/flaml/tune/spark/utils.py#L48

I think we can skip `check_spark` in the following cases:

1. When `use_ray = True`
2. When `n_concurrent_trials = 1`

### Code to reproduce:

```python
from flaml import AutoML
from sklearn.datasets import load_iris

automl = AutoML()
X, y =load_iris(as_frame=True, return_X_y=True)
automl.fit(X, y, task="classification")
```

Output:

```
check Spark installation...This line should appear only once.

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
23/01/05 14:41:46 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[flaml.automl.automl: 01-05 14:41:48] {2712} INFO - task = classification
[flaml.automl.automl: 01-05 14:41:48] {2714} INFO - Data split method: stratified
[flaml.automl.automl: 01-05 14:41:48] {2717} INFO - Evaluation method: cv
[flaml.automl.automl: 01-05 14:41:48] {2844} INFO - Minimizing error metric: log_loss
...
```

### PR DESCRIPTION
**Pull request by thinkall**
## Why are these changes needed?

Currently `check_spark` will be called when `use_spark=False` and `n_concurrent_trials=1` . Which creates unnecessary spark session. With this PR, only when `use_spark=True` or (`n_concurrent_trials>1` and ray is not available) will `check_spark` be called.

## Related issue number

Closes #871 

## Checks

- [x] I've used [pre-commit](https://microsoft.github.io/FLAML/docs/Contribute#pre-commit) to lint the changes in this PR, or I've made sure [lint with flake8](https://github.com/microsoft/FLAML/blob/816a82a1155b4de4705b21a615ccdff67c6da379/.github/workflows/python-package.yml#L54-L59) output is two 0s.
- [ ] I've included any doc changes needed for https://microsoft.github.io/FLAML/. See https://microsoft.github.io/FLAML/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

### CODE REVIEW

**Comment by harupy** [comment]
@thinkall Thanks for the quick fix!

**Comment by harupy** [comment]
@thinkall When will this fix be released?

**Comment by thinkall** [comment]
> @thinkall When will this fix be released?

We have a few other fixes in progress, I think they will be released together in version 1.1.1. I'm not sure about the ETA, maybe in a week or two? @sonichi may have more info on this.

**Review by sonichi — APPROVED** [review]

**Comment by sonichi** [comment]
> > @thinkall When will this fix be released?
> 
> We have a few other fixes in progress, I think they will be released together in version 1.1.1. I'm not sure about the ETA, maybe in a week or two? @sonichi may have more info on this.

We can release as soon as #871 and #869 are merged. The soonest is this weekend. Otherwise next week.

**Review by qingyun-wu — APPROVED** [review]
Looks good to me. Thanks for the fix!

**Pull request merged**
