### PR TITLE
disable tft logger

### PR DESCRIPTION
**Pull request by int-chaos**
#833 did not fix issue. new attempt to disable logger by adding set `log_interval=0` when `log=False`

### CODE REVIEW

**Review by sonichi — APPROVED** [review]

**Review by sonichi — COMMENTED** [review]
Is early_stop_callback invalid when log=False?

**Comment by sonichi** [comment]
Why don't we disable logging until the issue in pytorch-forecasting is fixed?

**Comment by sonichi** [comment]
> Why don't we disable logging until the issue in pytorch-forecasting is fixed?

I did that in #837

**Comment by int-chaos** [comment]
> > Why don't we disable logging until the issue in pytorch-forecasting is fixed?
> 
> I did that in #837

sounds good, will close PR

**Pull request closed without merging**
